=== Ze1598/Scrape-Worten/XML_DTD/daily_sales.dtd
<!ELEMENT daily_sales (clients, sales)>
<!ELEMENT clients (client+)>
<!ELEMENT client (name, address, contacts)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT contacts (contact+)>
<!ELEMENT contact (#PCDATA)>
<!ELEMENT sales (sale+)>
<!ELEMENT sale (products, order_price, shipping, final_price, delivery_address, invoice_address)>
<!ELEMENT products (product+)>
<!ELEMENT product (#PCDATA)>
<!ELEMENT product_id (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT order_price (#PCDATA)>
<!ELEMENT shipping (#PCDATA)>
<!ELEMENT final_price (#PCDATA)>
<!ELEMENT delivery_address (#PCDATA)>
<!ELEMENT invoice_address (#PCDATA)>

<!ATTLIST daily_sales day CDATA #REQUIRED
					month CDATA #REQUIRED
					year CDATA #REQUIRED
					store CDATA #REQUIRED
					local CDATA #REQUIRED
					tin CDATA #REQUIRED>
<!ATTLIST client id_c ID #REQUIRED
					tin_c CDATA #REQUIRED>
<!ATTLIST address locality CDATA #REQUIRED>
<!ATTLIST contact type CDATA #REQUIRED>
<!ATTLIST sale id_s CDATA #REQUIRED
					client IDREF #REQUIRED
					unit CDATA #REQUIRED>
<!ATTLIST product quantity CDATA #REQUIRED>
<!ATTLIST delivery_address locality CDATA #IMPLIED>
<!ATTLIST invoice_address locality CDATA #IMPLIED>

=== Ze1598/Scrape-Worten/XML_DTD/daily_sales.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE daily_sales SYSTEM "daily_sales.dtd">
<daily_sales day="26" month="6" year="2018" store="WORTEN" local="STA. CATARINA" tin="503630330">

	<clients>

		<client id_c="C1" tin_c="119120364">
			<name>Patricia Brown</name>
			<address locality="I">625 Oak St., Dawnstar IL 61914</address>
			<contacts>
				<contact type="PHONE NUMBER">800-555-5669</contact>
				<contact type="EMAIL">patricia_brown@email.com</contact>
			</contacts>
		</client>

		<client id_c="C2" tin_c="386931498">
			<name>Jennifer Davis</name>
			<address locality="P">890 Main St., Pythonville LA 29947</address>
			<contacts>
				<contact type="PHONE NUMBER">568-555-6051</contact>
				<contact type="EMAIL">jennifer_davis@email.com</contact>
			</contacts>
		</client>

		<client id_c="C3" tin_c="201728958">
			<name>Michael Smith</name>
			<address locality="H">732 High St., Valyria KY 97152</address>
			<contacts>
				<contact type="PHONE NUMBER">516-555-4615</contact>
				<contact type="EMAIL">michael_smith@email.com</contact>
			</contacts>
		</client>

		<client id_c="C4" tin_c="513672385">
			<name>Barbara Williams</name>
			<address locality="W">212 Cedar St., Sunnydale CT 74983</address>
			<contacts>
				<contact type="PHONE NUMBER">998-555-7385</contact>
				<contact type="EMAIL">barbara_williams@email.com</contact>
			</contacts>
		</client>

		<client id_c="C5" tin_c="361113513">
			<name>Eric Williams</name>
			<address locality="A">969 High St., Atlantis VA 34075</address>
			<contacts>
				<contact type="PHONE NUMBER">900-555-3205</contact>
				<contact type="EMAIL">eric_williams@email.com</contact>
			</contacts>
		</client>

	</clients>

	<sales>

		<sale id_s="S1" client="C3" unit="EURO">
			<products>
				<product quantity="8">P1969822</product>
				<product quantity="3">P9042590</product>
				<product quantity="8">P6989884</product>
			</products>
			<order_price>3520.0</order_price>
			<shipping>47.5</shipping>
			<final_price>3567.5</final_price>
			<delivery_address></delivery_address>
			<invoice_address locality="Z">121 Hill St., Braavos UT 92474</invoice_address>
		</sale>

		<sale id_s="S2" client="C2" unit="EURO">
			<products>
				<product quantity="1">P6892632</product>
				<product quantity="8">P9862574</product>
			</products>
			<order_price>4712.0</order_price>
			<shipping>22.5</shipping>
			<final_price>4734.5</final_price>
			<delivery_address locality="W">838 Main St., Balmora MT 56526</delivery_address>
			<invoice_address locality="W">173 Main St., Springfield RI 55924</invoice_address>
		</sale>

		<sale id_s="S3" client="C4" unit="EURO">
			<products>
				<product quantity="6">P6867320</product>
				<product quantity="3">P7856282</product>
			</products>
			<order_price>480.0</order_price>
			<shipping>22.5</shipping>
			<final_price>502.5</final_price>
			<delivery_address></delivery_address>
			<invoice_address locality="L">607 Washington St., Blackwater NH 97183</invoice_address>
		</sale>

		<sale id_s="S4" client="C5" unit="EURO">
			<products>
				<product quantity="3">P8034556</product>
			</products>
			<order_price>1920.0</order_price>
			<shipping>7.5</shipping>
			<final_price>1927.5</final_price>
			<delivery_address></delivery_address>
			<invoice_address></invoice_address>
		</sale>

		<sale id_s="S5" client="C5" unit="EURO">
			<products>
				<product quantity="7">P4562858</product>
				<product quantity="9">P3614060</product>
				<product quantity="2">P5429083</product>
			</products>
			<order_price>842.0</order_price>
			<shipping>45.0</shipping>
			<final_price>887.0</final_price>
			<delivery_address></delivery_address>
			<invoice_address></invoice_address>
		</sale>

	</sales>

</daily_sales>

=== Ze1598/Scrape-Worten/XML_HTML_CSS/daily_sales.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE daily_sales SYSTEM "daily_sales.dtd">
<daily_sales day="6" month="10" year="2018" store="WORTEN" local="STA. CATARINA" tin="503630330">

	<clients>

		<client id_c="C1" tin_c="184023148">
			<name>Michael Arnold</name>
			<address locality="Y">191 Main St., Mordor IL 72160</address>
			<contacts>
				<contact type="PHONE NUMBER">292-555-1875</contact>
				<contact type="EMAIL">michael_arnold@email.com</contact>
			</contacts>
		</client>

		<client id_c="C2" tin_c="403623802">
			<name>Eric Harris</name>
			<address locality="P">619 Park St., Winterfell VA 99000</address>
			<contacts>
				<contact type="PHONE NUMBER">568-555-6051</contact>
				<contact type="EMAIL">eric_harris@email.com</contact>
			</contacts>
		</client>

		<client id_c="C3" tin_c="561783254">
			<name>Corey Jefferson</name>
			<address locality="V">433 Elm St., Westworld TX 61967</address>
			<contacts>
				<contact type="PHONE NUMBER">900-555-3205</contact>
				<contact type="EMAIL">corey_jefferson@email.com</contact>
			</contacts>
		</client>

		<client id_c="C4" tin_c="419083439">
			<name>Michael Smith</name>
			<address locality="Z">217 High St., Old-town IA 82767</address>
			<contacts>
				<contact type="PHONE NUMBER">470-555-2750</contact>
				<contact type="EMAIL">michael_smith@email.com</contact>
			</contacts>
		</client>

		<client id_c="C5" tin_c="892550975">
			<name>Maria Johnson</name>
			<address locality="G">826 Elm St., Epicburg NE 10671</address>
			<contacts>
				<contact type="PHONE NUMBER">777-555-8378</contact>
				<contact type="EMAIL">maria_johnson@email.com</contact>
			</contacts>
		</client>

	</clients>

	<sales>

		<sale id_s="S1" client="C2" unit="EURO">
			<products>
				<product quantity="5">P7507718</product>
				<product quantity="6">P7713997</product>
				<product quantity="8">P5840681</product>
			</products>
			<order_price>1264.0</order_price>
			<shipping>47.5</shipping>
			<final_price>1311.5</final_price>
			<delivery_address></delivery_address>
			<invoice_address locality="N">732 High St., Valyria KY 97152</invoice_address>
		</sale>

		<sale id_s="S2" client="C5" unit="EURO">
			<products>
				<product quantity="8">P8788975</product>
				<product quantity="1">P9271848</product>
				<product quantity="9">P6827803</product>
			</products>
			<order_price>12996.0</order_price>
			<shipping>45.0</shipping>
			<final_price>13041.0</final_price>
			<delivery_address></delivery_address>
			<invoice_address></invoice_address>
		</sale>

		<sale id_s="S3" client="C4" unit="EURO">
			<products>
				<product quantity="10">P1061173</product>
				<product quantity="9">P9915406</product>
				<product quantity="6">P3513176</product>
			</products>
			<order_price>840.0</order_price>
			<shipping>62.5</shipping>
			<final_price>902.5</final_price>
			<delivery_address locality="L">838 Main St., Balmora MT 56526</delivery_address>
			<invoice_address locality="L">607 Washington St., Blackwater NH 97183</invoice_address>
		</sale>

		<sale id_s="S4" client="C4" unit="EURO">
			<products>
				<product quantity="1">P8941962</product>
				<product quantity="6">P5401532</product>
			</products>
			<order_price>5076.0</order_price>
			<shipping>17.5</shipping>
			<final_price>5093.5</final_price>
			<delivery_address></delivery_address>
			<invoice_address locality="Q">519 Washington St., Olympus TN 32425</invoice_address>
		</sale>

		<sale id_s="S5" client="C1" unit="EURO">
			<products>
				<product quantity="7">P4608459</product>
				<product quantity="5">P2035381</product>
			</products>
			<order_price>3825.0</order_price>
			<shipping>30.0</shipping>
			<final_price>3855.0</final_price>
			<delivery_address locality="D">890 Main St., Pythonville LA 29947</delivery_address>
			<invoice_address locality="D">969 High St., Atlantis VA 34075</invoice_address>
		</sale>

	</sales>

</daily_sales>
