=== Ze1598/Scrape-Worten/XML_HTML_CSS/catalog.dtd
<!ELEMENT catalog (product+)>
<!ELEMENT product (name, pu, images, description, extra_info)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT pu (#PCDATA)>
<!ELEMENT images (image+)>
<!ELEMENT image EMPTY>
<!ELEMENT description (#PCDATA)>
<!ELEMENT extra_info (info+)>
<!ELEMENT info (#PCDATA)>

<!ATTLIST catalog store CDATA #REQUIRED>
<!ATTLIST product id ID #REQUIRED
				avail CDATA #REQUIRED
				link CDATA #REQUIRED>
<!ATTLIST link ref CDATA #REQUIRED>
<!ATTLIST image ref CDATA #REQUIRED>
<!ATTLIST info type CDATA #REQUIRED>

=== Ze1598/Scrape-Worten/XML_HTML_CSS/catalog.xml
<?xml version="1.0" encoding="iso-8859-15" ?>
<!DOCTYPE catalog SYSTEM "catalog.dtd">
<catalog store="Worten">

	<product id="P6457228" avail="In stock" link="https://www.worten.pt/gaming/ps4/jogos-ps4/jogo-ps4-god-of-war-edicao-normal-6457228">
		<name>Jogo PS4 God of War Edição Normal</name>
		<pu>69,99</pu>
		<images>
			<image ref="https://www.worten.pt/i/1e7d840027ba91c1baeeabb154872d47ad5f35af.jpg"/>
			<image ref="https://www.worten.pt/i/0f1161a51c49a293579e5df4b45e178a57bcbed0.jpg"/>
			<image ref="https://www.worten.pt/i/afb03aed0028120834d10d13a03ff0c208ca48ca.jpg"/>
			<image ref="https://www.worten.pt/i/86d9a1b679f9e7c5969e043aa737a23ac1fffa17.jpg"/>
		</images>
		<description>Product description not available</description>
		<extra_info>
			<info type="Category">Jogos PS4</info>
			<info type="Brand">SONY-COMPUTER</info>
			<info type="Weight">Information not available</info>
			<info type="Dimensions">Information not available</info>
			<info type="Color">Information not available</info>
			<info type="Stock">20</info>
		</extra_info>
	</product>


	<product id="P6435510" avail="Out of stock" link="https://www.worten.pt/gaming/nintendo-switch/jogos-nintendo-switch/jogo-nintendo-switch-the-binding-of-isaac-afterbirth-6435510">
		<name>Jogo Nintendo Switch The Binding of Isaac: Afterbirth</name>
		<pu>49,99</pu>
		<images>
			<image ref="https://www.worten.pt/i/cf6acaadbb8d3a7c6f12f92c415698b06d3b1c63.jpg"/>
		</images>
		<description>Product description not available</description>
		<extra_info>
			<info type="Category">Jogos Nintendo Switch</info>
			<info type="Brand">INFOCAPITAL</info>
			<info type="Weight">Information not available</info>
			<info type="Dimensions">Information not available</info>
			<info type="Color">Information not available</info>
			<info type="Stock">0</info>
		</extra_info>
	</product>


	<product id="P6349217" avail="In stock" link="https://www.worten.pt/gaming/nintendo-switch/jogos-nintendo-switch/jogo-nintendo-switch-fire-emblem-warriors-6349217">
		<name>Jogo Nintendo Switch Fire Emblem Warriors</name>
		<pu>59,99</pu>
		<images>
			<image ref="https://www.worten.pt/i/75cd57a8e89dd3c541abb9dea64676dfc2d2f924.jpg"/>
		</images>
		<description>Product description not available</description>
		<extra_info>
			<info type="Category">Jogos Nintendo Switch</info>
			<info type="Brand">NINTENDO</info>
			<info type="Weight">Information not available</info>
			<info type="Dimensions">Information not available</info>
			<info type="Color">Information not available</info>
			<info type="Stock">28</info>
		</extra_info>
	</product>

</catalog>

=== Ze1598/Scrape-Worten/XML_DTD/catalog.xml
<?xml version="1.0" encoding="iso-8859-10" ?>
<!DOCTYPE catalog SYSTEM "catalog.dtd">
<catalog store="Worten">

	<product id="P5981717" avail="Disponível" link="https://www.worten.pt/ultimas-unidades/portatil-hibrido-12-6-asus-t303ua-56dhdsb1-5981717">
		<name>Portátil Híbrido 12.6'' ASUS T303UA-56DHDSB1</name>
		<pu>€1137,00</pu>
		<images>
			<image ref="https://www.worten.pt/i/78e498aa15d9b5c644a7229ab3882e326f9fcf6f.jpg"/>
			<image ref="https://www.worten.pt/i/24d1bf079d0d9e3896c41c4961e3922b0e484bba.jpg"/>
			<image ref="https://www.worten.pt/i/152054e64bda073797eb4d4fb5e1d69612acc499.jpg"/>
			<image ref="https://www.worten.pt/i/fc654a131b2c4928e344792bb992d9b8f8e2a49b.jpg"/>
		</images>
		<description>O computador Asus Transformer 3 Pro T303UA é um dispositivo híbrido de grande elegância que pode ser utilizado como um computador portátil ou como um tablet, de acordo com as necessidades do utilizador. Apresenta teclado destacável para facilitar a escrita, bem como ecrã tátil LCD LED de 12,6” com resolução WQHD+ de 2880 x 1920 píxeis e revestimento antibrilho. O processador Dual Core Intel Core i5-6200U a 2,3 GHz e os 8 GB de memória RAM fazem deste computador Asus Transformer 3 Pro T303UA uma excelente ferramenta de trabalho e, em simultâneo, um ótimo equipamento de entretenimento. O mecanismo de dobradiça instalado na parte traseira possibilita a colocação do computador Asus Transformer 3 Pro T303UA na posição vertical sobre qualquer superfície plana, para maior comodidade e conforto de utilização. Integra também placa gráfica Intel HD Graphics 520 para executar de forma exemplar qualquer videojogo ou aplicação gráfica. Outras características: disco SSD de 256 GB; sistema operativo Windows 10; Wi-Fi; Bluetooth 4.1; duas câmaras de 13 MP (traseira) e 2 MP (frontal); leitor de cartões de memória; USB 3.0; HDMI; porta Thunderbolt; sistema de som estéreo de 2 W; áudio Sonic Master Premium. Garantia de dois anos.A Worten destaca: computador híbrido de grande elegância; teclado destacável; ecrã tátil LCD LED de 12,6” com resolução WQHD+ de 2880 x 1920 píxeis e revestimento antibrilho; processador Dual Core Intel Core i5-6200U a 2,3 GHz; 8 GB de memória RAM; gráfica Intel HD Graphics 520; disco SSD de 256 GB; duas câmaras de 13 MP (traseira) e 2 MP (frontal); USB 3.0; HDMI; porta Thunderbolt; Wi-Fi; Bluetooth 4.1.</description>
		<extra_info>
			<info type="Category">Últimas Unidades</info>
			<info type="Brand">ASUS</info>
			<info type="Weight">1.1 Kg</info>
			<info type="Dimensions">0.8*29.8*20.8 cm</info>
			<info type="Color">Cinza/Metal</info>
			<info type="Stock">15</info>
		</extra_info>
	</product>


	<product id="P5797258" avail="Disponível" link="https://www.worten.pt/informatica/computadores/mini-pcs/raspberry-pi3-model-b-1gb-5797258">
		<name>RASPBERRY-PI3 Model B 1GB</name>
		<pu>€40,99</pu>
		<images>
			<image ref="https://www.worten.pt/i/567266d1ac2b6261a8a53760d0c78af687a6340f.jpg"/>
			<image ref="https://www.worten.pt/i/aef3a9fbd1e2cb2e6583c16201944929d9ae8061.jpg"/>
		</images>
		<description>Perfeito para os seus projetos e com maior poder de processamento e conetividade onboard face à versão anterior, o Raspberry PI 3 modelo B está equipado com processador Broadcom ARMv8 Cortex A53 Quad-Core a 1,2 GHz e apresenta 1 GB de memória RAM. O Pi 3 incorpora Wi-Fi e Bluetooth 4.1 para conetividade mais rápida, sem necessidade de qualquer dispositivo externo, e inclui chip de antena, armazenamento microSD e porta HDMI 1.4. Com estas características é recomendada a utilização de uma fonte de alimentação com o mínimo de 2.1 A para o seu correto funcionamento. Outras características: 4x porta USB 2.0; LED de estado; Jack áudio in/out de 3,5 mm. Garantia de dois anos. A Worten destaca:processador Broadcom ARMv8 Cortex A53 Quad-Core a 1,2 GHz; 1 GB de memória RAM; conetividade Wi-Fi e Bluetooth 4.1; armazenamento microSD; porta HDMI 1.4; 4x porta USB 2.0.</description>
		<extra_info>
			<info type="Category">Mini PC</info>
			<info type="Brand">RASPBERRY-PI</info>
			<info type="Weight">Information not available</info>
			<info type="Dimensions">3.5*12*7.5 cm</info>
			<info type="Color">Information not available</info>
			<info type="Stock">96</info>
		</extra_info>
	</product>


	<product id="P6356567" avail="Disponível" link="https://www.worten.pt/gaming/jogos-consolas/jogos-nintendo-ds-3ds/jogo-nintendo-3ds-fire-emblem-warriors-6356567">
		<name>Jogo Nintendo 3DS Fire Emblem Warriors</name>
		<pu>€44,99</pu>
		<images>
			<image ref="https://www.worten.pt/i/f6cef1ab66d7777611c0f501c4128b34236f34f4.jpg"/>
		</images>
		<description>Product description not available</description>
		<extra_info>
			<info type="Category">Jogos Nintendo DS / 3DS</info>
			<info type="Brand">NINTENDO</info>
			<info type="Weight">Information not available</info>
			<info type="Dimensions">Information not available</info>
			<info type="Color">Information not available</info>
			<info type="Stock">76</info>
		</extra_info>
	</product>

</catalog>
